language: java
jdk:
  - oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: "k/KcbYH0WBJuCaj3WltZ9iYwmXJZC8d5Xhi1gMvmD0IaoeCiJhwCX4vO6n86i5Abh12Bcd8zMgeAgCHevdo4IrM/lANhSrqUnnNvC52eYH13LL13F6XLxI2rFtKflkA/ZuxQpMJoXq03xmdOdgS276sEzaWocUR4WO48qx30pIp4dmZzxlWqHlyvrHgPqOXrFhfqrcHPgaEN7S8Hu9lQkYzgOR5xe4W7lO1e9I0oSAuOtrBPs7iYlEaMXqH7iNSrn1PA+wgQ0bo0/S9SDd+LA5iTlNe2QrPGZuHPGxsI0DDW6V1oS1ZPZ8jTfId6XSNDAECdbczWHGQA7UOjn9EnBosKs8ob8ApKQSU5bpjF7Z+lILmKTFFhK1ek9f6HYNM4Cim5ngbSGgIx1U3FrBntwcc/hxwSNTl8Y6RoT7SYNl+NYcyxjNyQie1CzNBuhE0lMFAoe/9jio0uYDAL4MCI1Kx/yAwHzE5jZcHg0PBzcGAEQUoOgmgguZhxIPyNBpYHtn1pf74dXkO0oKCD8YdIRc4LvUFmsbovEWiT55nOxRzKipPaCEfdfTRdUJvbgG/VrYZoyr2de8Eo2uPUtX8/f2NhyvHMMuqpVWmE7rZSz2El8ijvOhNBx5Ado5wOIh7sSc5CQ/KdG74iNHWYHLk9J6DAR0VjOmzlBfsMD46Wnkk="
  app: j2ee-esgi
  on:
    repo: CNadjim/BreizhLinkJEE